feature - color tiles screen
beersheba/flutter-demo pull request #2
Opened 2022-01-05 22:21 UTC by beersheba

Сверстать четыре квадрата и кнопку. Цвета квадратов по кнопке меняются на случайные.

До нажатия
![image](https://user-images.githubusercontent.com/13087114/148297681-3a910103-5da5-4036-8b1d-eed8fa91a1bb.png)

После нажатия
![image](https://user-images.githubusercontent.com/13087114/148297783-75ca600e-1aea-4a54-aec4-c4a95db15f39.png)

2022-01-07 03:52 UTC, dkrutskikh requested changes

2022-01-07 03:52 UTC, dkrutskikh commented on lib/widgets/tile.dart
> +  getColor() {
@beersheba почему у этой функции не описан возвращаемый тип?

2022-01-07 03:52 UTC, dkrutskikh commented on lib/widgets/tile.dart
> +      color: getColor(),
@beersheba функция getColor меняет состояние виджета сайд эффектом, из-за этого становиться неочевидно почему квадрат меняет цвет пока не посмотрим в код Tiles виджета. Можете перепроектировать этот момент?

2022-01-09 06:38 UTC, beersheba commented on lib/widgets/tile.dart
> +  getColor() {
Cгенерировал метод с помощью IDE, подумал что это ок.

2022-01-09 07:04 UTC, beersheba commented on lib/widgets/tile.dart
> +      color: getColor(),
@dkrutskikh вынес установку цвета наружу, изменил tile на stateless

2022-01-09 07:57 UTC, dkrutskikh approved these changes

2022-01-09 07:57 UTC, dkrutskikh commented on lib/screens/tiles.dart
> +  List<Color> colors = List.filled(4, Colors.grey);
@beersheba в цело ок, но все-же инициализацию состояния лучше делать в методе InitState

2022-01-09 07:57 UTC, dkrutskikh commented on lib/screens/tiles.dart
> +Color generateColor() {
@beersheba либо делаем этот метод приватным тк он нужен только в этом виджете, либо выносим в отдельный файл для будущего переиспользования

2022-01-09 07:57 UTC, dkrutskikh commented on lib/screens/tiles.dart
> +          onPressed: () => setState(() {
@beersheba такие функции я рекомендую всегда выносить в отдельный метод для:

1) уменьшаем билд метод в котором остается только верстка
2) это часть бизнес логики и ее лучше анализировать в отдельном методе

2022-01-09 09:26 UTC, beersheba commented on lib/screens/tiles.dart
> +          onPressed: () => setState(() {
вынес

2022-01-09 09:27 UTC, beersheba commented on lib/screens/tiles.dart
> +Color generateColor() {
вынес в отдельный файл

2022-01-09 09:27 UTC, beersheba commented on lib/screens/tiles.dart
> +  List<Color> colors = List.filled(4, Colors.grey);
ок

2022-01-09 09:54 UTC, merged